import HighrLight from "@/components/hightlight/HightLight";
function Page() {
    return (
        <div className="w-full">
            <div className=" text-2xl">project name</div>
            <div className="w-full">
                <div className="">title</div>
                <div className="w-full">
                    <div className="html">
                        <div>HTML</div>
                        <HighrLight language="xml" children='<label for="last-name">Last name</label>' />
                    </div>
                    <div className="css">
                        <div>CSS</div>
                        <HighrLight
                            language="css"
                            children={`body {
    background-image: url(/mainbg.svg);
    background-size: auto;
    background-repeat: repeat;
    color: #fff;
    /* cursor: url(https://cur.cursors-4u.net/cursors/cur-2/cur116.cur), progress; */
}`}
                        />
                    </div>
                    <div className="js">
                        <div>javascript</div>
                        <HighrLight
                            children={`<SyntaxHighlighter language="javascript" style={vscDarkPlus}>
    {children}
</SyntaxHighlighter>
export const metadata = {
    title: "Home ",
    description: "Generated by create next app",
};
`}
                        />
                    </div>
                </div>
            </div>
        </div>
    );
}

export default Page;
